
package org.example.proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ebankService", targetNamespace = "http://web.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EbankService {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertion", targetNamespace = "http://web.example.org/", className = "org.example.proxy.Convertion")
    @ResponseWrapper(localName = "convertionResponse", targetNamespace = "http://web.example.org/", className = "org.example.proxy.ConvertionResponse")
    @Action(input = "http://web.example.org/ebankService/convertionRequest", output = "http://web.example.org/ebankService/convertionResponse")
    public double convertion(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param id
     * @return
     *     returns org.example.proxy.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://web.example.org/", className = "org.example.proxy.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://web.example.org/", className = "org.example.proxy.GetAccountResponse")
    @Action(input = "http://web.example.org/ebankService/getAccountRequest", output = "http://web.example.org/ebankService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<org.example.proxy.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://web.example.org/", className = "org.example.proxy.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://web.example.org/", className = "org.example.proxy.GetAccountsResponse")
    @Action(input = "http://web.example.org/ebankService/getAccountsRequest", output = "http://web.example.org/ebankService/getAccountsResponse")
    public List<Account> getAccounts();

}
