
package org.example.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "EbankServiceService", targetNamespace = "http://web.example.org/", wsdlLocation = "http://localhost:4545/EbankService?wsdl")
public class EbankServiceService
    extends Service
{

    private static final URL EBANKSERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException EBANKSERVICESERVICE_EXCEPTION;
    private static final QName EBANKSERVICESERVICE_QNAME = new QName("http://web.example.org/", "EbankServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:4545/EbankService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EBANKSERVICESERVICE_WSDL_LOCATION = url;
        EBANKSERVICESERVICE_EXCEPTION = e;
    }

    public EbankServiceService() {
        super(__getWsdlLocation(), EBANKSERVICESERVICE_QNAME);
    }

    public EbankServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EBANKSERVICESERVICE_QNAME, features);
    }

    public EbankServiceService(URL wsdlLocation) {
        super(wsdlLocation, EBANKSERVICESERVICE_QNAME);
    }

    public EbankServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EBANKSERVICESERVICE_QNAME, features);
    }

    public EbankServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EbankServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EbankService
     */
    @WebEndpoint(name = "ebankServicePort")
    public EbankService getEbankServicePort() {
        return super.getPort(new QName("http://web.example.org/", "ebankServicePort"), EbankService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EbankService
     */
    @WebEndpoint(name = "ebankServicePort")
    public EbankService getEbankServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web.example.org/", "ebankServicePort"), EbankService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EBANKSERVICESERVICE_EXCEPTION!= null) {
            throw EBANKSERVICESERVICE_EXCEPTION;
        }
        return EBANKSERVICESERVICE_WSDL_LOCATION;
    }

}
